[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

# Override strict mypy settings for legacy code
[tool.mypy]
disallow_untyped_decorators = false
disallow_untyped_defs = false

[tool.poetry]
authors = ["Denis Khamitov <hamitov.97@mail.ru>"]
description = "Graphical user interface for biological experiment orchestration and device control."
license = "MIT"
name = "bioexperiment-gui"
packages = [
  {from = "src", include = "bioexperiment_gui"}
]
readme = "README.md"
repository = "https://github.com/denis240997/bio_tools"
version = "0.1.0"

[tool.poetry.dependencies]
bioexperiment-experiment = {develop = true, path = "../bioexperiment-experiment"}
bioexperiment-tools = {develop = true, path = "../bioexperiment-tools"}
python = ">=3.12,<3.13"
ttkbootstrap = "^1.10.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.4"

[tool.poetry.scripts]
bioexperiment-gui = "bioexperiment_gui:main"
