# Pre-commit hooks configuration
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter (replaces black, isort, flake8, etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      # Run the formatter only - formatting is auto-fixable
      # Linting should be run manually with `task lint` or `task check`
      - id: ruff-format
        types_or: [python, pyi]

  # Mypy - Static type checker (optional - can be skipped with SKIP=mypy)
  # These are informational type hints that don't block functionality
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-pyserial==3.5.0.20240527
          - munch-stubs==0.1.3
          - pydantic==2.5.0
        args: [--config-file=pyproject.toml, --explicit-package-bases, --no-error-summary]
        # Only check the strict async package, exclude legacy packages
        files: ^packages/bioexperiment-tools-async/src/
        exclude: ^(examples/|gui\.py|.*/tests/)
        # Make it non-blocking for commits
        verbose: true
        stages: [manual]  # Run only when explicitly called with --hook-stage manual

  # TOML sorting - Keep pyproject.toml files organized
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        args: [--in-place, --all]

  # General file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^\.gitignore$
      - id: end-of-file-fixer
        exclude: ^\.gitignore$
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=lf]

  # Notebook output stripping
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
