site_name: BioExperiment Suite
site_url: https://denis240997.github.io/bio_tools/
repo_url: https://github.com/denis240997/bio_tools
repo_name: denis240997/bio_tools
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - toc.follow

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue grey
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Navigation structure
nav:
  # - Getting Stared:
  #     - Installation: getting_started/installation.md
  #     - Quick Start: getting_started/quick_start.md
  - Examples:
      - examples/index.md
  #     - examples/pump.md
  #     - examples/spectrophotometer.md
  #     - examples/discover_devices.md
  #     - examples/setting_up_experiment.md
  #     - examples/advanced_experiment.md
  - API Reference:
      - api/index.md
      - Interfaces:
          - api/interfaces/index.md
          - api/interfaces/serial_connection.md
          - api/interfaces/spectrophotometer.md
          - api/interfaces/pump.md
      - Tools: api/tools.md
      - Experiment:
          - api/experiment/index.md
          - api/experiment/actions.md
          - api/experiment/experiment.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            members_order: source

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
