[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

# Override strict mypy settings for legacy code
[tool.mypy]
disallow_untyped_decorators = false
disallow_untyped_defs = false

[tool.poetry]
authors = ["Denis Khamitov <hamitov.97@mail.ru>"]
description = "Tools and interfaces for biological experiment devices including pumps and spectrophotometers."
include = [
  {path = "src/bioexperiment_tools/device_interfaces.json"},
  {path = "src/bioexperiment_tools/py.typed"}
]
license = "MIT"
name = "bioexperiment-tools"
packages = [
  {from = "src", include = "bioexperiment_tools"}
]
readme = "README.md"
repository = "https://github.com/denis240997/bio_tools"
version = "0.1.0"

[tool.poetry.dependencies]
loguru = "^0.7.2"
munch = "^4.0.0"
pyserial = "^3.5"
python = ">=3.12,<3.13"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
munch-stubs = "^0.1.2"
ruff = "^0.5.4"
types-pyserial = "^3.5.0.20240527"
