[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
python_version = "3.11"
strict_equality = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.poetry]
authors = ["Denis Khamitov <hamitov.97@mail.ru>"]
description = "Async tools and interfaces for biological experiment devices including pumps and spectrophotometers."
include = [
  {path = "src/bioexperiment_tools_async/device_configs.json"},
  {path = "src/bioexperiment_tools_async/py.typed"}
]
license = "MIT"
name = "bioexperiment-tools-async"
packages = [
  {from = "src", include = "bioexperiment_tools_async"}
]
readme = "README.md"
repository = "https://github.com/denis240997/bio_tools"
version = "0.1.0"

[tool.poetry.dependencies]
loguru = "^0.7.2"
pydantic = "^2.5.0"
pydantic-settings = "^2.1.0"
pyserial-asyncio = "^0.6"
python = ">=3.11,<4.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
pytest = "^8.3.4"
pytest-asyncio = "^0.23.0"
pytest-cov = "^4.0.0"
pytest-mock = "^3.12.0"
ruff = "^0.5.4"
types-pyserial = "^3.5.0.20240527"

[tool.pytest.ini_options]
addopts = "--cov=bioexperiment_tools_async --cov-report=term-missing --cov-report=html"
asyncio_mode = "auto"
python_classes = ["Test*"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
testpaths = ["tests"]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
fixable = ["ALL"]
ignore = ["B904", "C901", "PLR0912", "PLR0913", "PLR0915", "S101", "TRY003"]
select = ["A", "ARG", "B", "BLE", "C4", "COM", "E", "ERA", "F", "FBT", "G", "I", "ICN", "N", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "Q", "RET", "RSE", "RUF", "S", "SIM", "SLF", "T20", "TCH", "TID", "TRY", "UP", "W"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*" = ["PLR2004", "S101", "SLF001"]
