[tool.ruff.lint]
fixable = ["ALL"]
unfixable = ["F401"]

[tool.ruff]
line-length = 120

[tool.poetry]
name = "bioexperiment-experiment"
version = "0.1.0"
description = "Experiment orchestration framework for biological experiments with actions, measurements, and conditions."
license = "MIT"
authors = ["Denis Khamitov <hamitov.97@mail.ru>"]
readme = "README.md"
repository = "https://github.com/denis240997/bio_tools"
packages = [
    { include = "bioexperiment_experiment", from = "src"},
]
include = [
    { path = "src/bioexperiment_experiment/py.typed"},
]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
bioexperiment-tools = {path = "../bioexperiment-tools", develop = true}
loguru = "^0.7.2"
websockets = { version = "^14.0", optional = true }
python-dotenv = "^1.0.1"

[tool.poetry.extras]
websocket = ["websockets"]

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

